kind: Template
apiVersion: v1
metadata:
  name: "%SVC_NAME%-%STAND%-template"
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: '%SVC_NAME%'
      labels:
        app: '%SVC_NAME%'
      namespace: '%NAMESPACE%'
    spec:
      repliccc: 1
      strategy:
        type: Recreate
      selector:
        app: '%SVC_NAME%'
      template:
        metadata:
          name: '%SVC_NAME%'
          labels:
            app: '%SVC_NAME%'
        spec:
          nodeName: ''
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - '%SVC_NAME%'
                    topologyKey: kubernetes.io/hostname
          containers:
          - envFrom:
              - configMapRef:
                  name: '%SVC_NAME%'
            image: '%IMAGE%:%TAG%'
            imagePullPolicy: Always
            importPolicy:
              insecure: "true"
            name: '%SVC_NAME%'
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
              - mountPath: /etc/keydb
                name: '%SVC_NAME%'
                readOnly: true
          volumes:
            - configMap:
                defaultMode: 420
                name: '%SVC_NAME%'
              name: '%SVC_NAME%'
  - kind: Service
    apiVersion: v1
    metadata:
      name: '%SVC_NAME%'
      labels:
        app: '%SVC_NAME%'
    spec:
      type: ClusterIP
      ports:
        - name: 6379-port
          port: 6379
          protocol: TCP
          targetPort: 6379
      selector:
        app: '%SVC_NAME%'
