global:
  scrape_interval: 15s # default: 1m
  evaluation_interval: 15s # default: 1m
  # scrape_timeout: 10s (default)

scrape_configs:
  - job_name: pods
    metrics_path: /metrics/prometheus
    scheme: https
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - target_label: __metrics_path__
        replacement: /metrics/prometheus
