kind: Template
apiVersion: v1
metadata:
  name: "%SVC_NAME%-template"
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "%SVC_NAME%"
      labels:
        app: "%SVC_NAME%"
      namespace: "%NAMESPACE%"
    spec:
      repliccc: 1
      strategy:
        type: Rolling
      selector:
        app: "%SVC_NAME%"
      template:
        metadata:
          name: "%SVC_NAME%"
          labels:
            app: "%SVC_NAME%"
        spec:
          containers:
            - image: "%IMAGE%:%TAG%"
              imagePullPolicy: Always
              importPolicy:
                insecure: "true"
              name: "%SVC_NAME%"
              annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/metrics_path: /metrics
                prometheus.io/scrape_scheme: http
              ports:
                - containerPort: 9115
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 1m
                  memory: 256Mi
          #serviceAccountName: "%SVC_NAME%-rdbo"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "%SVC_NAME%"
      labels:
        app: "%SVC_NAME%"
    spec:
      type: ClusterIP
      ports:
        - name: 9115-port
          port: 9115
          protocol: TCP
          targetPort: 9115
      selector:
        app: "%SVC_NAME%"
