global:
  scrape_interval: 15s # default: 1m
  evaluation_interval: 15s # default: 1m
  scrape_timeout: 15s # default: 10s

scrape_configs:
  - job_name: pods
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - admc-cert
            - audt-cert
            - ccch-cert
            - crls-cert
            - dbzm-cert
            - drrr-common
            - drrr-cert
            - drfs-cert
            - evau-cert
            - evo-cert
            - ips-cert
            - lpet-cert
            - nsdp-cert
            - oapi-gord-cert
            - online-web-cert
            - orid-cert
            - pnb-cert
            - rrcn-cert
            - rrrp-atm-cert
            - rrrp-chat-cert
            - rrrp-cm-cert
            - rrrp-corp-cert
            - rrrp-fils-cert
            - rrrp-nfo-cert
            - rrrp-payr-cert
            - rrrp-ppro-cert
            - rrrp-react-cert
            - rrrp-rmb-cert
            - rrrp-sggo-cert
            - scrr-cert
            - svng-cert
            - tcom-cert
            - retail-certprod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_scheme]
        regex: (https?)
        target_label: __scheme__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_metrics_port]
        regex: ^$
        replacement: 8080
        target_label: __meta_kubernetes_pod_annotation_prometheus_io_metrics_port
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_metrics_port]
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_annotation_openshift_io_deployment_config_name]
        target_label: dc
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_label_git_version]
        target_label: imgtag
      - source_labels: [__meta_kubernetes_pod_labelpresent_owner, __meta_kubernetes_pod_label_owner]
        regex: true;(.*)
        target_label: owner
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "^ZUUL::EXCEPTION:(Connect_to_.+|.+_failed_to_respond.+)$"
        action: drop
  - job_name: pods-extra
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - admc-cert
            - audt-cert
            - ccch-cert
            - crls-cert
            - dbzm-cert
            - drrr-common
            - drrr-cert
            - drfs-cert
            - evau-cert
            - evo-cert
            - ips-cert
            - lpet-cert
            - nsdp-cert
            - oapi-gord-cert
            - online-web-cert
            - orid-cert
            - pnb-cert
            - rrcn-cert
            - rrrp-atm-cert
            - rrrp-chat-cert
            - rrrp-cm-cert
            - rrrp-corp-cert
            - rrrp-fils-cert
            - rrrp-nfo-cert
            - rrrp-payr-cert
            - rrrp-ppro-cert
            - rrrp-react-cert
            - rrrp-rmb-cert
            - rrrp-sggo-cert
            - scrr-cert
            - svng-cert
            - tcom-cert
            - retail-certprod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_extra_metrics_path]
        #source_labels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_extra_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_scheme]
        regex: (https?)
        target_label: __scheme__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_metrics_port]
        regex: ^$
        replacement: 8080
        target_label: __meta_kubernetes_pod_annotation_prometheus_io_metrics_port
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_metrics_port]
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_annotation_openshift_io_deployment_config_name]
        target_label: dc
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_label_git_version]
        target_label: imgtag
      - source_labels: [__meta_kubernetes_pod_labelpresent_owner, __meta_kubernetes_pod_label_owner]
        regex: true;(.*)
        target_label: owner
